### ISSUE TITLE
fetchngs pipeline not working on scRNAseq

### ISSUE THREAD

**Issue by archieandrews10** [nf-core/fetchngs#32] opened 2021-08-20 15:53 UTC
Hi there!

I have used fetchngs with no problems for downloading RNAseq data from SRA. However, when I tried the same with scRNAseq data from SRA. The pipeline ended saying "Pipeline completed successfully-", but when I opened the results folder, it had the "IDS_NOT_DOWNLOADED.txt" containing the input IDs. This was tried with the following script;

#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --mem=4gb
#SBATCH --job-name=ids8-download
#SBATCH --error=job.%J.err
#SBATCH --output=job.%J.out
#SBATCH --partition=tmp_anvil,batch

module load nextflow
module load singularity

# The job command(s):
# nextflow run nf-core/fetchngs --input ids8.txt -profile singularity
nextflow run nf-core/fetchngs --input ids8.txt -profile singularity

This was tried on following SRA Id's
SRX7278088
SRX7278087
SRX7278086
SRX7278085
SRX7278084
SRX7278083
SRX7278082
SRX7278081

Can anybody troubleshoot this and provide a way to make it work.

UPDATE: The fetchngs pipeline does not seem to work on any other datasets besides RNASeq. Tested pipeline on exome sequencing datasets and single-cell RNAsequencing datasets. It does not download datasets, but completes the job saying it has successfully completed the pipeline from execution.

regards
Arch

**Comment by archieandrews10** [comment] 2021-08-22 22:56
@drpatelh Can you help with the abive issue?

**Comment by Midnighter** [comment] 2022-11-24 12:33
I just tried this with your input and it seems to download the files just fine. Was this also your experience?

**Comment by drpatelh** [comment] 2023-05-05 08:18
Closing as unable to reproduce. We also added explicit support for 10x data in https://github.com/nf-core/fetchngs/issues/144 which should hopefully fix the issue. Please feel free to re-open or create a separate issue if the problem persists.

**Closed by drpatelh** 2023-05-05 08:18 UTC
Labels: bug
