### ISSUE TITLE
Errors downloading scrnaseq data using Amazon Genomics CLI (version 1.5.2)

### ISSUE THREAD

**Issue by jhgraber** [nf-core/fetchngs#130] opened 2022-11-23 20:03 UTC
### Description of the bug

Hello-
I’m fairly new to the [#fetchngs](https://nfcore.slack.com/archives/C024915L4KB) workflow, and am trying to use it to download and prepare a specific 10X-format single cell data set (BioProject [PRJNA589484](https://s3.console.aws.amazon.com/s3/buckets/agc-012870262837-us-east-1?region=us-east-1&prefix=fetchngs/PRJNA589484/&showversions=false)).  This is a rather large data set, with 8 samples that each are about 70-80 GB in size.  I’m working with the AGC (aws genomics command-line-interface) to make this go, and am a bit stymied still.I’ve worked around time out problems on the FTP download and also max file size on the SRATOOL override by using custom configuration file with these settings
withName: ‘SRA_FASTQ_FTP’ {
    ext.args = ‘--retry 5 --continue-at - --max-time 12000’
  }
  withName: ‘SRATOOLS_PREFETCH’ {
    ext.args = ‘-X 100000000’
  }
The problem that I’m now having is getting the split of data to occur and then successfully return the files to the target s3 bucket.  The default behavior has been to return only one file for each sample.  As these are quite large, I haven’t pulled them off of the s3 bucket yet to test the exact content.  I’ve made some progress now by again modifying the custom nextflow.config with the following:
withName: ‘SRATOOLS_FASTERQDUMP’ {
    ext.args = ‘--split-files --include-technical’
  }
I’m pretty sure that the “include-technical” got me to the successful split, but now the workflow is crashing with error.  I was able to find the successfully split files in the working directory.
In tracing through the log file, the specific error that is happening is this:
Nov-22 09:32:05.506 [Actor Thread 8] ERROR nextflow.extension.OperatorEx - @unknown
groovy.lang.MissingMethodException: No signature of method: java.util.ArrayList.getName() is applicable for argument types: () values: []
Possible solutions: getAt(groovy.lang.Range), getAt(java.lang.String), getAt(int), getAt(int), getAt(java.lang.String), getAt(java.util.Collection)
So my questions are
am i missing something that would make this work correctly?
has anyone else used this workflow to pull scRNAseq data successfully in any context?
is there anything I need to be aware of in running it with AGC that might also be causing issues?
Should I also add this as an issue on the github page for this workflow?
Thanks in advance for any help that can be provided

Here is the cextflow config contents
process {
    withName: 'SRA_FASTQ_FTP' {
        ext.args = '--retry 5 --continue-at - --max-time 12000'    
    }
    withName: 'SRATOOLS_PREFETCH' {
        ext.args = '-X 100000000'
    }
    withName: 'SRATOOLS_FASTERQDUMP' {
        ext.args = '--split-files --include-technical'
    }
}

Here is the Manifest.json contents
{
  "mainWorkflowURL": "https://github.com/nf-core/fetchngs.git",
  "inputFileURLs": [
    "inputs.json"
  ],
  "engineOptions": "-r 1.8 -c ./project/nextflow.config -profile docker"
}

### Command used and terminal output

```console
agc workflow run fetchngs -c fetchCtx1

The process runs to the point of fasterq-dump, but then gives an error.  The nextflow log will be included here
```

### Relevant files

[Archive.zip](https://github.com/nf-core/fetchngs/files/10078829/Archive.zip)

### System information

Amazon Genomics CLI, version 1.5.2, which runs Nextflow 22.04.3
Run with docker container engine
Executor awsbatch, through agc
Version 1.8 of nf-core/fetchngs

**Comment by drpatelh** [comment] 2023-04-25 10:27
Thanks for the details @jhgraber  and apologies for the late response. This appears to be a duplicate of https://github.com/nf-core/fetchngs/issues/144 

I will close this for now but will bear in mind the details you have dumped here when adding the functionality.

**Closed by drpatelh** 2023-04-25 10:27 UTC
Labels: bug
