### ISSUE TITLE
sra_ids_to_runinfo.py: command not found

### ISSUE THREAD

**Issue by ollieeknight** [nf-core/fetchngs#180] opened 2023-07-17 07:40 UTC
### Description of the bug

fetchngs fails at the first stage, and I'm not totally sure why. My environment is set up as such:
```
export PATH=/data/gpfs-1/users/knighto_c/work/bin/jdk-17.0.7/bin:$PATH
export PATH=/data/gpfs-1/users/knighto_c/work/bin/nextflow:$PATH
export NXF_SINGULARITY_CACHEDIR=/data/gpfs-1/users/knighto_c/work/bin/nextflow/singularity_cache
export NXF_WORK=/fast/users/knighto_c/scratch/tmp/nf_work
```

Does anyone have any advice or guidane? Thank you so much!

### Command used and terminal output

```console
nextflow run nf-core/fetchngs -profile singularity --input ids.csv --outdir outs

ERROR ~ Error executing process > 'NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (PRJNA823746)'

Caused by:
  Process `NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO (PRJNA823746)` terminated with an error exit status (127)

Command executed:

  echo PRJNA823746 > id.txt
  sra_ids_to_runinfo.py \
      id.txt \
      PRJNA823746.runinfo.tsv \


  cat <<-END_VERSIONS > versions.yml
  "NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO":
      python: $(python --version | sed 's/Python //g')
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_TMPDIR as environment variable will not be supported in the future, use APPTAINERENV_TMPDIR instead
  WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_NXF_DEBUG as environment variable will not be supported in the future, use APPTAINERENV_NXF_DEBUG instead
  .command.sh: line 4: sra_ids_to_runinfo.py: command not found

Work dir:
  /fast/users/knighto_c/scratch/tmp/nf_work/35/d752bf1517ce799dde6723309996e3

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```
```


### Relevant files

[nextflow.log.txt](https://github.com/nf-core/fetchngs/files/12066964/nextflow.log.txt)


### System information

_No response_

**Comment by drpatelh** [comment] 2024-01-17 13:21
Duplicate of https://github.com/nf-core/fetchngs/issues/142

**Comment by ollieeknight** [comment] 2024-01-19 15:10
> Duplicate of #142


apologies, it's a duplicate, because i never figured it out :(

**Comment by drpatelh** [comment] 2024-01-29 17:43
Ah, that's a shame. In any case, it looks like an infrastructure related issue that needs to be fixed upstream and not a pipeline related issue.

I will close this but please feel free to join the [nf-core Slack Workspace](https://nf-co.re/join) where you can ask for help in the #fetchngs channel.

**Closed by drpatelh** 2024-01-29 17:43 UTC
Labels: bug
