### ISSUE TITLE
why does input file need to end in .txt

### ISSUE THREAD

**Issue by ojziff** [nf-core/fetchngs#118] opened 2022-10-18 20:56 UTC
### Description of the bug

minor point, but why does --input have to match pattern ^\S+\.txt$ Since the input is just a single column of SRR identifiers, it could be csv or tsv.

### Command used and terminal output

```console
nextflow run nf-core/fetchngs \
--input srr_id.txt \
--outdir reads \
--force_sratools_download -profile crick -r 1.7 -resume
```

Referring to:
see 
https://github.com/nf-core/fetchngs/blob/b79cde2fb58ec3bee3ef20124c6ade0c2f263d7d/nextflow_schema.json#L19 and https://github.com/nf-core/fetchngs/blob/0c43cc787290d88c9127af8281bb69554d905012/nextflow_schema.json#L21

**Comment by Midnighter** [comment] 2022-10-19 10:59
I don't see a good reason. Was there one that I forgot about @drpatelh ?

**Comment by ojziff** [comment] 2022-10-19 11:10
see 
https://github.com/nf-core/fetchngs/blob/b79cde2fb58ec3bee3ef20124c6ade0c2f263d7d/nextflow_schema.json#L19 and https://github.com/nf-core/fetchngs/blob/0c43cc787290d88c9127af8281bb69554d905012/nextflow_schema.json#L21

**Comment by drpatelh** [comment] 2022-11-02 10:38
Somewhat a duplicate of https://github.com/nf-core/fetchngs/issues/111

**Comment by drpatelh** [comment] 2022-11-04 11:06
Fixed in https://github.com/nf-core/fetchngs/pull/115/commits/d67b3ef6eaf437c7a22da800fcb0d26f19d0a9a7

**Closed** 2022-11-04 11:06 UTC
Labels: enhancement
