### ISSUE TITLE
Downloading of controlled data

### ISSUE THREAD

**Issue by JiaGengChang** [nf-core/fetchngs#107] opened 2022-07-14 07:12 UTC
### Description of feature

I would like to request for the ability to pass in our dbGAP credentials through the --ngc flag of SRAtools so as to be able to download controlled data.

**Comment by drpatelh** [comment] 2022-11-04 10:33
Hi @JiaGengChang ! Can you send us an example command of how you would do this outside of the pipeline please and any other credentials settings you need to use.

**Comment by celinesin** [comment] 2023-03-13 21:48
My command is:

prefetch $currSRA --ngc $path_key

where 
$currSRA is a SRA id
$path_key is a *.ngc file

**Comment by drpatelh** [comment] 2023-04-25 10:32
Duplicate of https://github.com/nf-core/fetchngs/issues/138

**Closed by drpatelh** 2023-04-25 10:32 UTC
Labels: enhancement
