### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by BeckmannA** [nf-core/fetchngs#179] opened 2023-07-14 16:07 UTC
### Description of the bug

Hi I'm trying to use the fetchngs pipeline and am first testing the pipeline on my institution's HPC. 

### Command used and terminal output

```console
# My input
nextflow run nf-core/fetchngs -profile test,singularity --outdir test

# Terminal output
N E X T F L O W  ~  version 22.10.6
Launching `https://github.com/nf-core/fetchngs` [fabulous_easley] DSL2 - revision: 2706782874 [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  nf-core/fetchngs v1.10.0-g2706782
------------------------------------------------------
Core Nextflow options
  revision                  : master
  runName                   : fabulous_easley
  containerEngine           : singularity
  launchDir                 : /rsrch4/home/nc-ndc/NDCD
  workDir                   : /rsrch4/home/nc-ndc/NDCD/work
  projectDir                : /rsrch4/home/nc-ndc/pabeckmann/.nextflow/assets/nf-core/fetchngs
  userName                  : pabeckmann
  profile                   : test,singularity
  configFiles               : /rsrch4/home/nc-ndc/pabeckmann/.nextflow/assets/nf-core/fetchngs/nextflow.config

Input/output options
  input                     : https://raw.githubusercontent.com/nf-core/test-datasets/fetchngs/sra_ids_test.csv
  outdir                    : test

Institutional config options
  config_profile_name       : Test profile
  config_profile_description: Minimal test dataset to check pipeline function

Max job request options
  max_cpus                  : 2
  max_memory                : 6.GB
  max_time                  : 6.h

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use nf-core/fetchngs for your analysis please cite:

* The pipeline
  https://doi.org/10.5281/zenodo.5070524

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://github.com/nf-core/fetchngs/blob/master/CITATIONS.md
------------------------------------------------------
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_RUNINFO_TO_FTP                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP                                                            -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:CUSTOM_SRATOOLSNCBISETTINGS -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_PREFETCH           -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_FASTERQDUMP        -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_TO_SAMPLESHEET                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_MERGE_SAMPLESHEET                                                    -
[-        ] process > NFCORE_FETCHNGS:SRA:MULTIQC_MAPPINGS_CONFIG                                                  -
[-        ] process > NFCORE_FETCHNGS:SRA:CUSTOM_DUMPSOFTWAREVERSIONS                                              -
Pulling Singularity image https://depot.galaxyproject.org/singularity/sra-tools:2.11.0--pl5321ha49a11a_3 [cache /rsrch4/home/nc-ndc/NDCD/work/singularity/depot.galaxyproject.org-singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img]
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_IDS_TO_RUNINFO                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_RUNINFO_TO_FTP                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_FASTQ_FTP                                                            -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:CUSTOM_SRATOOLSNCBISETTINGS -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_PREFETCH           -
[-        ] process > NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:SRATOOLS_FASTERQDUMP        -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_TO_SAMPLESHEET                                                       -
[-        ] process > NFCORE_FETCHNGS:SRA:SRA_MERGE_SAMPLESHEET                                                    -
[-        ] process > NFCORE_FETCHNGS:SRA:MULTIQC_MAPPINGS_CONFIG                                                  -
[-        ] process > NFCORE_FETCHNGS:SRA:CUSTOM_DUMPSOFTWAREVERSIONS                                              -
Pulling Singularity image https://depot.galaxyproject.org/singularity/sra-tools:2.11.0--pl5321ha49a11a_3 [cache /rsrch4/home/nc-ndc/NDCD/work/singularity/depot.galaxyproject.org-singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img]
Pulling Singularity image https://depot.galaxyproject.org/singularity/python:3.9--1 [cache /rsrch4/home/nc-ndc/NDCD/work/singularity/depot.galaxyproject.org-singularity-python-3.9--1.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /rsrch4/home/nc-ndc/NDCD/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'NFCORE_FETCHNGS:SRA:FASTQ_DOWNLOAD_PREFETCH_FASTERQDUMP_SRATOOLS:CUSTOM_SRATOOLSNCBISETTINGS (ncbi-settings)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name depot.galaxyproject.org-singularity-sra-tools-2.11.0--pl5321ha49a11a_3.img.pulling.1689350011945 https://depot.galaxyproject.org/singularity/sra-tools:2.11.0--pl5321ha49a11a_3 > /dev/null
  status : 255
  message:
    FATAL:   Error making http request: Head "https://depot.galaxyproject.org/singularity/sra-tools:2.11.0--pl5321ha49a11a_3": read tcp 10.68.68.7:34654->128.118.250.14:443: read: connection reset by peer
```

### System information

 N E X T F L O W
      version 22.10.6 build 5843
      created 23-01-2023 23:20 UTC (17:20 CDT)
      cite doi:10.1038/nbt.3820
      http://nextflow.io

Hardware: HPC
Executor: LSF 10.1
Container Engine: Singularity
OS: RHEL 7.9
Version 1.10.0

**Comment by pmoris** [comment] 2023-08-25 08:00
From the error message it appears that singularity could not connect to the galaxy repository housing the image. If running the pull command manually (`singularity shell https://depot.galaxyproject.org/singularity/sra-tools:2.11.0--pl5321ha49a11a_3`) results in the same error, then the issue is likely due to the configuration of the HPC system or its network/firewall. 

Depending on the way the HPC is configured, it could be that the problem only occurs on worker nodes during job execution, but not on login nodes. In any case, I'd reach out to your HPC's help desk and ask them if they block the download of singularity images from https://depot.galaxyproject.org/singularity/.

As a workaround, you could download the image manually on your own device and upload it to the HPC yourself. You'd also need to instruct nextflow to look for the image in a specific location rather than downloading it from galaxy, as described [here](https://www.nextflow.io/docs/latest/singularity.html):

> Nextflow caches those images in the singularity directory in the pipeline work directory by default. However it is suggest to provide a centralised caching directory by using either the NXF_SINGULARITY_CACHEDIR environment variable or the singularity.cacheDir setting in the Nextflow config file.

If you use the environment variable, be sure to export it or define it in your job submission script, rather than just setting it in your local shell. E.g. `export NXF_SINGULARITY_CACHEDIR=/path/to/cachedir`, and also ensure it is in a location that your HPC worker nodes can access.

**Comment by drpatelh** [comment] 2024-01-17 13:23
Yep, I agree this is an infrastructure and not pipeline related issue. Will close this for now but please feel free to join the [nf-core Slack Workspace](https://nf-co.re/join) for any future questions/issues. We have an #fetchngs channel where you can get more real-time help.

**Closed by drpatelh** 2024-01-17 13:23 UTC
Labels: bug
